FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# In local dev, we usually mount the volume, 
# but this is for a standalone container if needed.
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
